### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by bwaidelich** [Format-D/FormatD.HotspotEditor#4]
This _seems_ to be a great package but unfortunately I could not get it to work properly.
There is some [Hotspots.ts](https://github.com/Format-D/FormatD.HotspotEditor/blob/main/Resources/Private/Scripts/HotspotEditorFrontend/Hotspots.ts) file but it does not seem to be used at all

A short Howto would be very very helpful

**Comment by bweinzierl** [comment]
Hi @bwaidelich,
we had the plan to provide a usable implementation with a separate package. It is only used within a internal boilerplate currently.
Maybe this is the right time to finally do so. I will get back to you...

**Comment by bwaidelich** [comment]
Awesome, thanks for the quick feedback!
If it turns out to be too much work, some pointers in the README might already help though

**Comment by bweinzierl** [comment]
Hi @bwaidelich, we will provide something tomorrow at the latest...

**Comment by bwaidelich** [comment]
Awesome!

**Comment by bweinzierl** [comment]
Hi @bwaidelich ,
i added an implementation example that we will refactor into a ready to run plugin over the next days.
Also i sent you a message in Neos Slack
https://github.com/Format-D/FormatD.HotspotContent

**Comment by bweinzierl** [comment]
@bwaidelich 
We have created a package and released a first running version:
Package Name: `formatd/hotspot-content`
Hope that helps :)

**Comment by bwaidelich** [comment]
> We have created a package and released a first running version

Fantastic, thank you!
For reference: https://github.com/Format-D/FormatD.HotspotContent
